# coding: utf8

# Source Document (transactions records)
db.define_table('operation',
    Field('id', type='id'),
    Field('customer_id', type=db.customer, default=0),
    #Field('acreedorid', type='reference acreedores', default=0),
    Field('document_id', type=db.document, default=0),
    Field('prefix', type='integer', default=0),
    Field('number', type='integer', default=0),
    #Field('condicionpagoid', type='integer', comment='Formas de Pago'),
    #Field('condicion', type='string', length=50),
    #Field('importe', type='double'),
    #Field('saldo', type='double'),
    Field('date', type='datetime'),
    Field('issue_date', type='datetime'),
    Field('due_date', type='datetime'),
    Field('detail', type='string', length=60, comment='Observaciones'),
    Field('tipo', type='string', length=1),
    Field('invalidated', type='boolean', default=False),
    #Field('fondoid', type='integer', default=0),
    #Field('centrocostoid', type='integer', default=0),
    Field('observation', type='string', length=50),
    Field('description', type='string', length=10),
    ##Field('user_id', type='integer'),
    Field('hora', type='datetime', default=request.now),
    #Field('subdeudorid', type='integer'),
    #Field('vendedorid', type='integer'),
    #Field('impreso', type='boolean', default=False),
    #Field('jurisdiccionid', type='integer'),
    format="%(id)s",
    migrate=migrate)

# Source document items (posting)
# ie.: "traditional" line items
db.define_table('movement',
    Field('id', type='id'),
    Field('operation_id', type=db.operation),
    Field('concepto_id', type=db.concept),
    #Field('rate_id', type='integer', default=0),
    Field('quantity', type='double', default=1),
    Field('amount', type='double', default=0),
    Field('movement_id', type='integer', default=None),
    Field('detail', type='string', length=255),
    Field('value', type='double', ),
    Field('discount', type='double',  ),
    Field('tax_rate', type='double', ),
    format="%(id)s",
    migrate=migrate)
