# coding: utf8

# Customer Relationship Management

# customers/clients:
db.define_table('deudores',
    Field('deudorid', type='id', comment='C\xc3\xb3digo de Cliente'),
    Field('codigo', type='string', length=5),
    Field('deudor', type='string', length=100),
    Field('razon', type='string', length=50, comment='Raz\xc3\xb3n Social, Nombre o Denominaci\xc3\xb3n'),
    Field('direccion', type='string', length=100, comment='Direcci\xc3\xb3n Postal'),
    Field('cp', type='string', length=4),
    Field('localidad', type='string', length=20),
    Field('provinciaid', type='integer', default=0),
    Field('pais', type='string', length=15),
    Field('fax', type='string', length=20, comment='N\xc3\xbamero de Tel\xc3\xa9fono para Fax'),
    Field('telefono', type='string', length=60, comment='Tel\xc3\xa9fonos'),
    Field('vendedorid', type='integer', default=0),
    Field('listaprecioid', type='integer', default=0),
    Field('cuit', type='string', length=20, comment='N\xc3\xbamero de CUIT'),
    Field('iva', type='integer', default=0),
    Field('condicionpagoid', type='integer', default=0),
    Field('cliente', type='integer', default=0),
    Field('factura', type='string', length=1, comment='Letra de Factura que se Emitir\xc3\xa1'),
    Field('ctacte', type='string', length=1, comment='Tipo de Cuenta Corriente'),
    Field('situacionid', type='reference situaciones', default=1, comment='Estado'),
    Field('grupoid', type='integer', default=1, comment='Grupo'),
    Field('observaciones', type='text'),
    Field('lugarentrega', type='text'),
    Field('nroproveedor', type='string', length=50),
    Field('alta', type='datetime', comment='Fecha de Alta/Inicio'),
    Field('baja', type='datetime', comment='Fecha de Baja'),
    Field('replica', type='boolean', default=False),
    Field('limitecc', type='double'),
    Field('limitech', type='double'),
    Field('jurisdiccionid', type='integer'),
    Field('limitedeuda', type='decimal(10,None)'),
    migrate=migrate)

# sub-customers ("sub-accounts")
db.define_table('subdeudores',
    Field('subdeudorid', type='integer'),
    Field('subdeudor', type='string', length=100),
    Field('deudorid', type='integer'),
    Field('codigo', type='string', length=5),
    Field('deudor', type='string', length=100),
    Field('razon', type='string', length=50),
    Field('direccion', type='string', length=100),
    Field('cp', type='string', length=4),
    Field('localidad', type='string', length=20),
    Field('provinciaid', type='integer'),
    Field('pais', type='string', length=15),
    Field('fax', type='string', length=20),
    Field('telefono', type='string', length=60),
    Field('cuit', type='string', length=20),
    Field('iva', type='integer'),
    Field('factura', type='string', length=1),
    Field('ctacte', type='string', length=1),
    Field('listaprecioid', type='integer'),
    Field('situacionid', type='integer'),
    Field('grupoid', type='integer'),
    Field('observaciones', type='text'),
    Field('lugarentrega', type='text'),
    Field('nroproveedor', type='string', length=50),
    Field('alta', type='datetime'),
    Field('baja', type='datetime'),
    Field('replica', type='boolean'),
    Field('limitecc', type='double'),
    Field('limitech', type='double'),
    Field('jurisdiccionid', type='integer'),
    Field('sexo', ),
    Field('nacimiento', type='date'),
    migrate=migrate)

# groups
db.define_table('grupos',
    Field('grupoid', type='id'),
    Field('grupo', type='string', length=50),
    Field('replica', type='boolean', default=False),
    migrate=migrate)

# contacts
db.define_table('contactos',
    Field('contactoid', type='id'),
    Field('contacto', type='string', length=100),
    Field('deudorid', type='integer'),
    Field('acreedorid', type='integer'),
    Field('sector', type='string', length=50),
    Field('telefono', type='string', length=100),
    Field('fax', type='string', length=100),
    Field('email', type='string', length=100),
    Field('horario', type='string', length=100),
    Field('direccion', type='string', length=50),
    Field('cp', type='string', length=50, comment='C\xc3\xb3digo Postal'),
    Field('localidad', type='string', length=50),
    Field('provincia', type='string', length=50),
    Field('observaciones', type='text'),
    migrate=migrate)
    
# memos messages
db.define_table('memos',
    Field('memoid', type='id'),
    Field('fecha', type='date'),
    Field('contactoid', type='integer', default=0),
    Field('motivo', type='string', length=50),
    Field('observaciones', type='text'),
    Field('usuarioid', type='integer', default=0),
    Field('replica', type='boolean', default=False),
    migrate=migrate)

# status (active, unactive, prospect, etc.)
db.define_table('situaciones',
    Field('situacionid', type='integer'),
    Field('situacion', type='string', length=30),
    primarykey=['situacionid'],
    migrate=migrate)

# salesman
db.define_table('vendedores',
    Field('vendedorid', type='id'),
    Field('vendedor', type='string', length=50),
    Field('telefono', type='string', length=50),
    Field('domicilio', type='string', length=50),
    Field('provincia', type='string', length=50),
    Field('notas', type='text'),
    migrate=migrate)
