# coding: utf8

# Human Resources management

db.define_table('personal',
    Field('personalid', type='double'),
    Field('nombre', type='string', length=40),
    Field('domicilio', type='string', length=40),
    Field('localidad', type='string', length=50),
    Field('codigopostal', type='string', length=4),
    Field('provincia', type='string', length=50),
    Field('telefono', type='string', length=12),
    Field('nacimiento', type='datetime'),
    Field('documento', type='string', length=15),
    Field('nacionalidad', type='string', length=50),
    Field('cuil', type='string', length=13),
    Field('sexo', type='string', length=1),
    Field('estadocivil', type='string', length=1),
    Field('alta', type='datetime'),
    Field('baja', type='datetime'),
    primarykey=['personalid'],
    migrate=migrate)

db.define_table('plantas',
    Field('plantaid', type='id'),
    Field('planta', type='string', length=250),
    migrate=migrate)

db.define_table('secciones',
    Field('seccionid', type='id'),
    Field('seccion', type='string', length=200),
    migrate=migrate)

db.define_table('sindicatos',
    Field('sindicatoid', type='id'),
    Field('sindicato', type='string', length=50),
    Field('descripcion', type='string', length=50),
    Field('porcentaje', type='integer', default=0, comment='Aporte Personal para el calculo de Aporte Sindical'),
    Field('patronal', type='integer', default=0, comment='Aporte Patronal'),
    Field('voluntario', type='integer', default=0, comment='Aporte Voluntario'),
    migrate=migrate)

db.define_table('legajos',
    Field('legajoid', type='id'),
    Field('personalid', type='integer', default=0),
    Field('hsextras', type='double', comment='Cantidad de Horas Extras'),
    Field('presentismo', type='double', comment='Importe del Premio por Presentismo'),
    Field('aumentogobierno', type='double', comment='Aumento del Gobierno (Mensualizados)'),
    Field('diasenfermedad', type='integer', default=0, comment='Cantidad de D\xc3\xadas por Enfermedad'),
    Field('dtopresentismo', type='double', comment='Importe del Descuento Presentismo'),
    Field('faltassinaviso', type='double'),
    Field('dtoaportes', type='double', comment='Importe del Descuento Aportes'),
    Field('antiguedad', type='double'),
    Field('viaticos', type='double', comment='Importe Viaticos'),
    Field('pganancia', type='double', comment='Importe del Porcentaje de Ganancia'),
    Field('escolaridad', type='integer', default=0, comment='Cantidad de Hijos para Ayuda Escolar'),
    Field('asignacionhijo', type='integer', default=0, comment='Cantidad de Hijos para Asignaci\xc3\xb3n Anual'),
    Field('vacaciones', type='double'),
    Field('sac', type='double', comment='Importe del Medio Aguinaldo'),
    Field('prenatal', type='integer', default=0),
    Field('categoriaid', type='integer', default=0),
    Field('obrasocialid', type='integer', default=0),
    Field('sindicatoid', type='integer', default=0),
    Field('cajaprevisionid', type='integer', default=0, comment='(Jubilaci\xc3\xb3n)'),
    Field('centrocostoid', type='integer', default=0),
    Field('ingreso', type='datetime'),
    Field('egreso', type='datetime'),
    Field('sueldo', type='double', comment='Sueldo B\xc3\xa1sico (Mensualizados)'),
    Field('antiguedadaños', type='integer'),
    Field('conyugue', type='boolean', default=False),
    Field('antiguedadmeses', type='integer'),
    Field('familianumerosa', type='boolean', default=False),
    Field('seccion', type='string', length=50),
    Field('codigo', type='string', length=20),
    Field('seccionid', type='integer', default=1),
    Field('cargoid', type='integer', default=1),
    Field('plantaid', type='reference plantas', default=1),
    migrate=migrate)

db.define_table('liquidaciones',
    Field('liquidacionid', type='id'),
    Field('liquidacion', type='string', length=50, comment='Tipo y Periodo'),
    Field('tipo', type='string', length=1),
    Field('sac', type='boolean', default=False),
    Field('vacaciones', type='boolean', default=False),
    Field('desde', type='datetime'),
    Field('hasta', type='datetime'),
    migrate=migrate)

db.define_table('novedades',
    Field('novedadid', type='id'),
    Field('legajoid', type='integer'),
    Field('conceptoid', type='integer'),
    Field('dato', type='double', default=0),
    Field('liquidacionid', type='integer', default=0),
    Field('alta', type='date'),
    Field('baja', type='date'),
    migrate=migrate)

db.define_table('obrassociales',
    Field('obrasocialid', type='double'),
    Field('obrasocial', type='string', length=30),
    Field('descripcion', type='string', length=10),
    Field('porcentaje', type='integer', default=0, comment='Porcentaje de Aporte'),
    Field('patronal', type='integer', default=0, comment='Aporte Patronal'),
    Field('voluntario', type='integer', default=0, comment='Aporte Voluntario?'),
    Field('adherente', type='integer', default=0, comment='Aporte por Adherente'),
    primarykey=['obrasocialid'],
    migrate=migrate)
    
db.define_table('cajasprevision',
    Field('cajaprevisionid', type='id'),
    Field('cajaprevision', type='string', length=50),
    Field('porcentaje', type='double', comment='Aporte personal para el calculo de Jubilaci\xc3\xb3n'),
    Field('aporte', type='integer', default=0, comment='Aporte patronal para el calculo de los Aportes'),
    Field('ley19032', type='integer', default=0),
    migrate=migrate)
    
db.define_table('cargos',
    Field('cargoid', type='id'),
    Field('cargo', type='string', length=200),
    migrate=migrate)
    
db.define_table('categorias',
    Field('categoriaid', type='double'),
    Field('categoria', type='string', length=30),
    Field('sueldo', type='double'),
    Field('valorhora', type='double'),
    Field('tipo', type='string', length=1),
    Field('jornalizado', type='boolean', default=False),
    Field('convenio', type='boolean', default=False),
    Field('alta', type='datetime'),
    Field('baja', type='datetime'),
    Field('convenioid', type='reference convenios'),
    Field('plantaid', type='reference plantas'),
    migrate=migrate)
    
db.define_table('columnas',
    Field('columnaid', type='id'),
    Field('columna', type='string', length=50),
    Field('abr', type='string', length=50),
    Field('orden', type='integer', default=0),
    Field('recibo', type='boolean', default=False),
    Field('remunerativo', type='boolean', default=False),
    Field('operacion', type='string', length=1),
    migrate=migrate)

db.define_table('familiares',
    Field('familiarid', type='id'),
    Field('nombre', type='string', length=100),
    Field('personalid', type='integer', comment='Empleado'),
    Field('parentesco', type='string', length=1),
    Field('cuil', type='string', length=13),
    Field('asignacion', type='boolean', default=False),
    Field('discapacitado', type='boolean', default=False),
    Field('escolaridad', type='boolean', default=False),
    Field('nacionalidad', type='string', length=15),
    Field('nacimiento', type='datetime', comment='Fec.Nac.'),
    Field('estadocivil', type='string', length=1, comment='Estado Civil'),
    Field('domicilio', type='string', length=25),
    migrate=migrate)
    
db.define_table('formulas',
    Field('formulaid', type='id'),
    Field('nombre', type='string', length=50),
    Field('formula', type='text'),
    Field('cantidad', type='text'),
    Field('importe', type='double'),
    Field('dato', type='double'),
    Field('formato', type='string', length=1),
    Field('texto', type='text'),
    migrate=migrate)
    
   
db.define_table('sueldos',
    Field('sueldoid', type='id'),
    Field('centrocostoid', type='integer'),
    Field('categoriaid', type='integer'),
    Field('legajoid', type='integer'),
    Field('conceptoid', type='reference conceptos'),
    Field('liquidacionid', type='integer'),
    Field('tipo', type='string', length=1),
    Field('sac', type='boolean', default=False),
    Field('cantidad', type='double'),
    Field('importe', type='double'),
    Field('desde', type='datetime'),
    Field('hasta', type='datetime'),
    Field('fijo', type='boolean', default=False),
    Field('liquidado', type='boolean', default=False),
    Field('formato', type='string', length=1),
    Field('texto', type='string', length=255),
    Field('convenioid', type='reference convenios'),
    Field('seccionid', type='reference secciones'),
    Field('cargoid', type='reference cargos'),
    Field('plantaid', type='reference plantas'),
    migrate=migrate)
