# coding: utf8

# Source Document types/categories (grouping ledgers)
# ie.: Invoice, Receipt, Purchase Order, pay stub, voucher, proof., etc.
db.define_table('comprobantes',
    Field('comprobanteid', type='integer', default=0),
    Field('comprobante', type='string', length=50),
    Field('talonarioid', type='integer', default=0),
    Field('abr', type='string', length=3),
    Field('tipo', type='string', length=1),
    Field('gravar', type='boolean', default=False),
    Field('discriminar', type='boolean', default=False),
    Field('sucursal', type='integer', default=0),
    Field('numero', type='integer', default=0),
    Field('entrada', type='boolean', default=False),
    Field('salida', type='boolean', default=False),
    Field('fiscal', type='boolean', default=False),
    Field('stock', type='boolean', default=False),
    Field('ctasctes', type='boolean', default=False),
    Field('contado', type='boolean', default=False),
    Field('debitos', type='boolean', default=False),
    Field('creditos', type='boolean', default=False),
    Field('facturas', type='boolean', default=False),
    Field('recibos', type='boolean', default=False),
    Field('remitos', type='boolean', default=False),
    Field('pedidos', type='boolean', default=False),
    Field('contable', type='boolean', default=False),
    Field('impresora', type='string', length=50),
    Field('lineas', type='integer', default=0),
    Field('fondoid', type='integer', default=0),
    Field('replicar', type='boolean', default=False),
    Field('replica', type='boolean', default=False),
    Field('notas', type='text'),
    Field('observaciones', type='text'),
    Field('descripcion', type='text'),
    Field('id', type='string', length=50),
    Field('caja', type='boolean', default=False),
    Field('reservas', type='boolean', default=False),
    Field('formularioid', type='integer'),
    Field('presupuestos', type='boolean', default=False),
    Field('senias', type='boolean', default=False),
    Field('copias', type='integer'),
    Field('confirmarimpresion', type='boolean', default=False),
    Field('interno', type='boolean', default=False),
    Field('invertir', type='boolean', default=False),
    Field('continuo', type='boolean', default=False),
    Field('multipleshojas', type='boolean', default=False),
    Field('preimpreso', type='boolean', default=False),
    primarykey=['comprobanteid'],
    migrate=migrate)

# Account reference/detail (lowest level of the Chart of Accounts)
# ie: products/services, payments, income, expenses, etc.
db.define_table('conceptos',
    Field('conceptoid', type='integer', default=0),
    Field('codigo', type='string', length=20),
    Field('concepto', type='string', length=250),
    Field('rubroid', type='integer', default=0),
    Field('subrubroid', type='integer'),
    Field('familiaid', type='integer'),
    Field('colorid', type='integer'),
    Field('talleid', type='integer'),
    Field('cantidad', type='integer', default=0),
    Field('importe', type='double', default=0),
    Field('alta', type='date'),
    Field('baja', type='date'),
    Field('alicuotaiva', type='double', default=21),
    Field('acreedorid', type='integer'),
    Field('deudorid', type='integer'),
    Field('cuentaid', type='integer', default=0),
    Field('medida', type='string', length=1),
    Field('deseado', type='double', default=0),
    Field('presentacion', type='string', length=100),
    Field('descripcion', type='text'),
    Field('entrada', type='boolean', default=False),
    Field('salida', type='boolean', default=False),
    Field('gravado', type='boolean', default=False),
    Field('stock', type='boolean', default=False),
    Field('unitario', type='boolean', default=False),
    Field('interno', type='boolean', default=False),
    Field('formapago', type='boolean', default=False),
    Field('impuesto', type='boolean', default=False),
    Field('ctasctes', type='boolean', default=False),
    Field('caja', type='boolean', default=False),
    Field('extra', type='boolean', default=False),
    Field('efectivo', type='boolean', default=False),
    Field('bancos', type='boolean', default=False),
    Field('recibo', type='string', length=50),
    Field('resumen', type='string', length=50),
    Field('abreviatura', type='string', length=50),
    Field('cantidadstock', type='double'),
    Field('replica', type='boolean', default=False),
    Field('coleccionid', type='integer'),
    Field('minimo', type='double'),
    Field('suspendido', type='boolean', default=False),
    Field('descuentos', type='boolean', default=False),
    Field('recargos', type='boolean', default=False),
    primarykey=['conceptoid'],
    migrate=migrate)

# Source Document (transactions records)
db.define_table('operaciones',
    Field('operacionid', type='id'),
    Field('deudorid', type='reference deudores', default=0),
    Field('acreedorid', type='reference acreedores', default=0),
    Field('detalle', type='string', length=60, comment='Observaciones'),
    Field('condicionpagoid', type='integer', comment='Formas de Pago'),
    Field('condicion', type='string', length=50),
    Field('importe', type='double'),
    Field('saldo', type='double'),
    Field('fecha', type='datetime'),
    Field('emision', type='datetime'),
    Field('comprobanteid', type='integer', default=0),
    Field('sucursal', type='integer', default=0),
    Field('numero', type='integer', default=0),
    Field('vencimiento', type='datetime'),
    Field('tipo', type='string', length=1),
    Field('cancelado', type='boolean', default=False, comment='Falso si pago diferido (df), verdadero si pago con efectivo (ef), ch o cc'),
    Field('procesado', type='boolean', default=False),
    Field('anulado', type='boolean', default=False),
    Field('fondoid', type='integer', default=0),
    Field('centrocostoid', type='integer', default=0),
    Field('modulo', type='integer', default=0, comment='Tabla relacionada'),
    Field('id', type='integer', default=0, comment='Apunta al PED / FAC / REM'),
    Field('observaciones', type='string', length=50),
    Field('descripcion', type='string', length=10),
    Field('cancelacion', type='boolean', default=False),
    Field('anulacion', type='boolean', default=False),
    Field('legajoid', type='integer'),
    Field('liquidacionid', type='integer'),
    Field('usuarioid', type='integer'),
    Field('hora', type='datetime'),
    Field('replica', type='boolean', default=False),
    Field('replicado', type='datetime'),
    Field('subdeudorid', type='integer'),
    Field('vendedorid', type='integer'),
    Field('impreso', type='boolean', default=False),
    Field('jurisdiccionid', type='integer'),
    migrate=migrate)

# Source document items (posting)
# ie.: "traditional" line items
db.define_table('movimientos',
    Field('movimientoid', type='integer', default=0),
    Field('operacionid', type='integer', default=0),
    Field('conceptoid', type='integer', default=0),
    Field('tarifaid', type='integer', default=0),
    Field('cantidad', type='double', default=0),
        Field('importe', type='decimal(10,2)', default=0),
    Field('discriminado', type='integer', default=0),
    Field('tabla', type='integer', default=0),
    Field('id', type='integer', default=0),
    Field('detalle', type='string', length=255),
    Field('valor', type='decimal(10,2)', default=0),
    Field('inicio', type='date'),
    Field('replica', type='boolean', default=False),
    Field('descuento', type='decimal(10,2)'),
    Field('recargo', type='decimal(10,2)'),
    primarykey=['movimientoid'],
    migrate=migrate)

# pricelists
db.define_table('listasprecio',
    Field('listaprecioid', type='integer', default=0),
    Field('listaprecio', type='string', length=50),
    Field('entrada', type='boolean', default=False),
    Field('salida', type='boolean', default=False),
    Field('replica', type='boolean', default=False),
    primarykey=['listaprecioid'],
    migrate=migrate)
    
# price "engine":
db.define_table('precios',
    Field('precioid', type='id'),
    Field('conceptoid', type='integer'),
    Field('rubroid', type='integer'),
    Field('vendedorid', type='integer'),
    Field('deudorid', type='integer'),
    Field('acreedorid', type='integer'),
    Field('grupoid', type='integer'),
    Field('situacionid', type='integer'),
    Field('fondoid', type='integer'),
    Field('tarifaid', type='integer', comment='Tipo de Envase'),
    Field('pagoid', type='integer', comment='Forma de Pago'),
    Field('comprobanteid', type='integer', comment='Tipo de Comprobante'),
    Field('listaprecioid', type='integer'),
    Field('gravado', type='boolean', default=False),
    Field('iva', type='integer'),
    Field('tipo', type='string', length=1),
    Field('valor', type='double', default=0, comment='Ingrese el valor a calcular'),
    Field('calcular', type='string', length=1),
    Field('operacion', type='string', length=50),
    Field('origen', type='string', length=1, comment='Campo sobre el cual se efectuaran las operaciones'),
    Field('condicion', type='string', length=2),
    Field('cantidad1', type='double'),
    Field('cantidad2', type='double'),
    Field('discriminar', type='boolean', default=False),
    Field('id', type='integer'),
    Field('prioridad', type='integer'),
    Field('formula', type='text'),
    Field('alicuotaiva', type='double'),
    migrate=migrate)

# points of sale
db.define_table('talonarios',
    Field('talonarioid', type='id'),
    Field('talonario', type='string', length=50),
    Field('sucursal', type='integer', default=0),
    Field('numero', type='integer', default=0),
    Field('cai', type='string', length=50),
    Field('vencimiento', type='datetime'),
    migrate=migrate)
